version: 2.1
orbs:
  win-slack: vela-games/win-slack@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1
  win: circleci/windows@4.1.1

filters: &filters
  tags:
    only: /.*/

jobs:
  command-tests-windows:
    executor: win/default
    steps:
      - win-slack/notify:
          mentions: "<!here> <!channel>"
          text: "Hello World"
          channel: "test"

workflows:
  test-deploy:
    jobs:
      - command-tests-windows:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: vela-games/win-slack
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - command-tests-windows
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
